browse_categories:
- Cloud infrastructure and services
code: https://github.com/search?q=topic%3Acloud-foundry+org%3Asignalfx+fork%3Atrue
data_signature: metric_source:"cloudfoundry"
description: Monitor Pivotal Cloud Foundry using multiple SignalFx integration options.
display_name: Pivotal Cloud Foundry
featured: true
in_app_categories:
- servicesMonitored
logo_large: /images/repos/cloudfoundry/img/integrations_pivotalcloudfoundry%402x.png
logo_small: /images/repos/cloudfoundry/img/integrations_pivotalcloudfoundry.png
project_url: https://github.com/signalfx/integrations/tree/master/cloudfoundry-pivotal
useLegacyBuild: true
