browse_categories:
- Compute
code: https://azure.microsoft.com/en-us/services/functions/
data_signature: metric_source:"azure_function_wrapper"
description: SignalFx's integration with Azure Functions.
display_name: Azure Functions
featured: false
in_app_categories:
- AzureServicesMonitored
logo_large: integration_azurefunctions@2x.png
logo_small: integration_azurefunctions.png
project_url: https://github.com/signalfx/integrations/tree/master/azure-functions
useLegacyBuild: true
