{ "display_name": "Cloud Foundry",
  "description": "Monitor Cloud Foundry using multiple SignalFx integration options.",
  "project_url": "https://github.com/signalfx/integrations/tree/master/cloudfoundry",
  "code": "https://github.com/search?q=topic%3Acloud-foundry+org%3Asignalfx+fork%3Atrue",
  "featured": true,
  "data_signature": "metric_source:\"cloudfoundry\"",
  "logo_large": "/images/repos/cloudfoundry/img/integrations_cloudfoundry%402x.png",
  "logo_small": "/images/repos/cloudfoundry/img/integrations_cloudfoundry.png",
  "in_app_categories": ["servicesMonitored"]
}
