code: https://github.com/search?q=topic%3Acloud-foundry+org%3Asignalfx+fork%3Atrue
data_signature: metric_source:"cloudfoundry"
description: Monitor Cloud Foundry using multiple SignalFx integration options.
display_name: Cloud Foundry
featured: true
in_app_categories:
- servicesMonitored
logo_large: /images/repos/cloudfoundry/img/integrations_cloudfoundry%402x.png
logo_small: /images/repos/cloudfoundry/img/integrations_cloudfoundry.png
project_url: https://github.com/signalfx/integrations/tree/master/cloudfoundry
useLegacyBuild: true
