browse_categories:
- Compute
- Containers
code: https://aws.amazon.com/eks/
data_signature: namespace:"AWS/EKS"
description: SignalFx's integration with Elastic Container Service for Kubernetes
  (EKS).
display_name: Amazon EKS
featured: false
in_app_categories:
- AWSservicesMonitored
logo_large: integration_amazoneks%402x.png
logo_small: integration_amazoneks.png
project_url: https://github.com/signalfx/integrations/tree/master/aws-eks
useLegacyBuild: true
