browse_categories:
- Networking & Content Delivery
code: https://aws.amazon.com/cloudfront/
data_signature: namespace:"AWS/CloudFront"
description: SignalFx's integration with AWS CloudFront.
display_name: AWS CloudFront
featured: false
in_app_categories:
- AWSservicesMonitored
logo_large: integration_awscloudfront.png
logo_small: integration_awscloudfront.png
project_url: https://github.com/signalfx/integrations/tree/master/aws-cloudfront
