{ "display_name":"Couchbase",
  "description": "Monitor Couchbase using the SignalFx collectd agent.",
  "project_url": "https://github.com/signalfx/integrations/tree/master/collectd-couchbase",
  "code": "https://github.com/signalfx/collectd-couchbase",
  "featured": false,
  "logo_small": "/images/repos/collectd-couchbase/img/integrations_couchbase.png",
  "logo_large": "/images/repos/collectd-couchbase/img/integrations_couchbase%402x.png",
  "data_signature": "plugin:\"couchbase\"",
  "in_app_categories": ["servicesMonitored"]
}
