#!/usr/bin/env python3

import json
import sys
from pathlib import Path

import yaml

TARGET = Path(sys.argv[1])


def convert():
    from_json = yaml.safe_load(TARGET.read_text())
    TARGET.write_text(yaml.dump(from_json))


print(f"Converting {TARGET}")
convert()
