browse_categories:
- Networking & Content Delivery
code: https://cloud.google.com/router
data_signature: service:"router"
description: SignalFx's integration with Google Cloud Router
display_name: Google Cloud Router
featured: false
in_app_categories:
- GCPServicesMonitored
logo_large: integration_googlecloudrouter%402x.png
logo_small: integration_googlecloudrouter.png
project_url: https://github.com/signalfx/integrations/tree/master/google-cloud-router
useLegacyBuild: true
