{ "display_name":"Java",
  "description": "The Java plugin for collectd embeds a Java virtual machine (JVM) into collectd and exposes the application programming interface (API) to Java programs.",
  "project_url": "https://github.com/signalfx/integrations/tree/master/collectd-java",
  "code": "https://github.com/signalfx/collectd/blob/master/src/java.c",
  "featured": false,
  "logo_large": "/images/repos/collectd-java/img/integrations_java.png",
  "logo_small": "/images/repos/collectd-java/img/integrations_java%402x.png",
  "data_signature": "plugin:\"GenericJMX\"",
  "in_app_categories": ["servicesMonitored"]
}
