code: https://github.com/signalfx/gateway
description: 'Aggregate metrics from different sources and formats and forward them
  to SignalFx.

  If you are an APM customer, install the Smart Gateway instead.'
display_name: SignalFx Gateway
featured: false
in_app_categories:
- essential
logo_large: /images/repos/gateway/img/integration_sfxgateway%402x.png
logo_small: /images/repos/gateway/img/integration_sfxgateway.png
project_url: https://github.com/signalfx/integrations/tree/master/gateway
useLegacyBuild: true
