browse_categories:
- Web
code: https://github.com/signalfx/fluent-bit-plugin
data_signature: ''
description: Produce log-based metrics using SignalFx plugin for Fluent Bit
display_name: Fluent Bit
featured: false
in_app_categories:
- servicesMonitored
logo_large: /images/repos/microsoft-iis/img/integration_fluentbit%402x.png
logo_small: /images/repos/microsoft-iis/img/integration_fluentbit.png
project_url: https://github.com/signalfx/fluent-bit-plugin/blob/master/README.md
useLegacyBuild: true
