browse_categories:
- Database
code: https://aws.amazon.com/dynamodb/
data_signature: namespace:"AWS/DynamoDB"
description: SignalFx's integration with Amazon DynamoDB.
display_name: Amazon DynamoDB
featured: false
in_app_categories:
- AWSservicesMonitored
logo_large: integration_awsdynamodb%402x.png
logo_small: integration_awsdynamodb.png
project_url: https://github.com/signalfx/integrations/tree/master/aws-dynamodb
useLegacyBuild: true
