browse_categories:
- Cloud infrastructure and services
- Application integration
code: https://github.com/signalfx/cloudwatch-event-forwarder
data_signature: ''
description: Send Amazon CloudWatch Events to SignalFx
display_name: Amazon CloudWatch Events
featured: false
in_app_categories:
- AWSservicesMonitored
logo_large: integration_cloudwatchevents%402x.png
logo_small: integration_cloudwatchevents.png
project_url: https://github.com/signalfx/cloudwatch-event-forwarder/blob/master/README.md