{ "display_name":"Azure Storage",
  "description": "SignalFx's integration with Azure Storage",
  "project_url": "https://github.com/signalfx/integrations/tree/master/azure-storage",
  "code": "https://azure.microsoft.com/en-us/services/storage/",
  "featured": false,
  "logo_large": "integrations_azurestorage.png",
  "logo_small": "integrations_azurestorage@2x.png",
  "data_signature": "resource_type:\"Microsoft.Storage/storageAccounts\"",
  "in_app_categories": ["AzureServicesMonitored"]
}
