browse_categories:
- Media Services & Solutions
- Analytics
code: https://aws.amazon.com/kinesis/
data_signature: namespace:"AWS/Kinesis"
description: SignalFx's integration with AWS Kinesis Streams.
display_name: AWS Kinesis Streams
featured: false
in_app_categories:
- AWSservicesMonitored
logo_large: integration_awskinesisstreams%402x.png
logo_small: integration_awskinesisstreams.png
project_url: https://github.com/signalfx/integrations/tree/master/aws-kinesis-streams
useLegacyBuild: true
