browse_categories:
- Analytics
code: https://github.com/signalfx/collectd-spark
data_signature: plugin:"apache_spark"
description: Monitor Spark cluster and applications using the SignalFx Smart Agent.
display_name: Apache Spark
featured: false
in_app_categories:
- servicesMonitored
logo_large: /images/repos/spark/img/integrations_apachespark%402x.png
logo_small: /images/repos/spark/img/integrations_apachespark.png
project_url: https://github.com/signalfx/integrations/tree/master/spark
useLegacyBuild: true
