browse_categories:
- Web
code: https://github.com/signalfx/collectd/blob/master/src/varnish.c
data_signature: plugin:"varnish"
description: Monitor Varnish using the SignalFx collectd agent.
display_name: Varnish
featured: false
in_app_categories:
- servicesMonitored
logo_large: /images/repos/collectd-varnish/img/integrations_varnish%402x.png
logo_small: /images/repos/collectd-varnish/img/integrations_varnish.png
project_url: https://github.com/signalfx/integrations/tree/master/collectd-varnish
useLegacyBuild: true
