browse_categories:
- Database
code: https://cloud.google.com/datastore
data_signature: service:"datastore"
description: SignalFx's integration with Google Cloud Datastore
display_name: Google Cloud Datastore
featured: false
in_app_categories:
- GCPServicesMonitored
logo_large: integration_googleclouddatastore%402x.png
logo_small: integration_googleclouddatastore.png
project_url: https://github.com/signalfx/integrations/tree/master/google-cloud-datastore
useLegacyBuild: true
