code: https://github.com/signalfx/pops
description: Aggregate metrics with different tokens from collectd, json, or protobuf
  and forward them to SignalFx.
display_name: SignalFx POPS (Point Of Presence Service)
featured: false
project_url: https://github.com/signalfx/integrations/tree/master/pops
useLegacyBuild: true
