browse_categories:
- Web
code: https://github.com/signalfx/signalfx-agent/tree/master/internal/monitors/windowsiis
data_signature: sf_metric:"web_service.total_method_requests_sec"
description: Monitor Microsoft Internet Information Services
display_name: Microsoft IIS
featured: false
in_app_categories:
- servicesMonitored
logo_large: /images/repos/microsoft-iis/img/integration_microsoftiis%402x.png
logo_small: /images/repos/microsoft-iis/img/integration_microsoftiis.png
project_url: https://github.com/signalfx/signalfx-agent/blob/master/docs/monitors/windows-iis.md
useLegacyBuild: true
