code: https://github.com/signalfx/signalfx-java
description: Java Library for SignalFx
display_name: SignalFx Java Library
featured: false
logo_large: /images/repos/lib-java/img/integrations_java%402x.png
logo_small: /images/repos/lib-java/img/integrations_java.png
project_url: https://github.com/signalfx/integrations/tree/master/lib-java
useLegacyBuild: true
