proxy:
    # Uncomment and enter value below to configure HTTP proxy.
    # http:

    # Uncomment and enter value below to configure HTTPS proxy.
    # https:

    # Uncomment below and enter IP or domains to exclude from proxying.
    # Multiple entries can be entered as a comma-separated list.
    # skip:

kubernetes:
  # Set to one of master or worker.
  role: master

  # Replace CLUSTER_NAME with the name of your cluster to be attached as a
  # dimension to all metrics.
  cluster: CLUSTER_NAME
