browse_categories:
- Networking & Content Delivery
code: https://aws.amazon.com/elasticloadbalancing/
data_signature: namespace:"AWS/ApplicationELB"
description: SignalFx's integration with Application Load Balancing (ALB).
display_name: Amazon ALB
featured: false
in_app_categories:
- AWSservicesMonitored
logo_large: integration_awsalb.png
logo_small: integration_awsalb.png
project_url: https://github.com/signalfx/integrations/tree/master/aws-alb
useLegacyBuild: true
