code: https://github.com/signalfx/signalfx-ruby
description: Programmatic interface in Ruby for SignalFx APIs.
display_name: SignalFx Ruby Library
featured: false
logo_large: /images/repos/lib-ruby/img/integrations_tuby%402x.png
logo_small: /images/repos/lib-ruby/img/integrations_ruby.png
project_url: https://github.com/signalfx/integrations/tree/master/lib-ruby
useLegacyBuild: true
