code: https://github.com/signalfx/collectd/blob/master/src/write_http.c
description: This output plugin submits values to an HTTP server using POST requests
  and encoding metrics with JSON or using the PUTVAL command described in collectd-unixsock(5).
display_name: write-http collectd plugin
featured: false
logo_large: /images/repos/collectd-write_http/img/integrations_collectd%402x.png
logo_small: /images/repos/collectd-write_http/img/integrations_collectd.png
project_url: https://github.com/signalfx/integrations/tree/master/collectd-write_http
useLegacyBuild: true
