{ "display_name":"Apache",
  "description": "Monitor Apache Webserver using the SignalFx collectd agent.",
  "project_url": "https://github.com/signalfx/integrations/tree/master/collectd-apache",
  "code": "https://github.com/signalfx/collectd/blob/master/src/apache.c",
  "featured": false,
  "logo_large": "/images/repos/collectd-apache/img/integrations_apache%402x.png",
  "logo_small": "/images/repos/collectd-apache/img/integrations_apache.png",
  "data_signature": "plugin:\"apache\"",
  "in_app_categories": ["servicesMonitored"]
}
