browse_categories:
- Development Tools
data_signature: metric_source:"gitlab"
description: Monitor GitLab using the SignalFx Smart Agent.
display_name: GitLab
featured: false
in_app_categories:
- servicesMonitored
logo_large: /images/repos/gitlab/img/integration_gitlab@2x.png
logo_small: /images/repos/gitlab/img/integration_gitlab.png
project_url: https://github.com/signalfx/integrations/tree/master/gitlab
useLegacyBuild: true
