browse_categories:
- Media Services & Solutions
- Analytics
code: https://aws.amazon.com/kinesis/data-analytics/
data_signature: namespace:"AWS/KinesisAnalytics"
description: SignalFx's integration with AWS Kinesis Analytics.
display_name: AWS Kinesis Analytics
featured: false
in_app_categories:
- AWSservicesMonitored
logo_large: integration_awskinesisanalytics%402x.png
logo_small: integration_awskinesisanalytics.png
project_url: https://github.com/signalfx/integrations/tree/master/aws-kinesis-analytics
