data_signature: cloud_provider_service:"EC2.Instances"
description: SignalFx AWS Optimizer.
display_name: AWS Optimizer
featured: false
in_app_categories:
- AWSservicesMonitored
logo_large: integration_optimizer.png
logo_small: integration_optimizer.png
project_url: https://github.com/signalfx/integrations/tree/master/aws-optimizer
useLegacyBuild: true
