browse_categories:
- Analytics
code: https://cloud.google.com/pubsub
data_signature: service:"pubsub"
description: SignalFx's integration with Google Cloud Pub/Sub
display_name: Google Cloud Pub/Sub
featured: false
in_app_categories:
- GCPServicesMonitored
logo_large: integration_googlecloudpubsub%402x.png
logo_small: integration_googlecloudpubsub.png
project_url: https://github.com/signalfx/integrations/tree/master/google-cloud-pubsub
