browse_categories:
- Containers
code: https://azure.microsoft.com/en-us/services/kubernetes-service/
data_signature: resource_type:"Microsoft.ContainerService/managedClusters"
description: SignalFx integration with Azure Kubernetes Service
display_name: Azure Kubernetes Service
featured: false
in_app_categories:
- AzureServicesMonitored
logo_large: integration_azurekubernetesservice%402x.png
logo_small: integration_azurekubernetesservice.png
project_url: https://github.com/signalfx/integrations/tree/master/azure-kubernetes-service
useLegacyBuild: true
