browse_categories:
- Cloud infrastructure and services
- Management Tools
code: https://aws.amazon.com/cloudwatch/
description: SignalFx's integration with Amazon Web Services.
display_name: Amazon Web Services
featured: false
in_app_categories:
- AWSservicesMonitored
logo_large: integration_aws.png
logo_small: integration_aws.png
project_url: https://github.com/signalfx/integrations/tree/master/aws
sort_order: 2
useLegacyBuild: true
