browse_categories:
- Analytics
code: https://cloud.google.com/bigquery
data_signature: service:"bigquery"
description: SignalFx's integration with Google BigQuery
display_name: Google BigQuery
featured: false
in_app_categories:
- GCPServicesMonitored
logo_large: integration_googlebigquery%402x.png
logo_small: integration_googlebigquery.png
project_url: https://github.com/signalfx/integrations/tree/master/google-bigquery
useLegacyBuild: true
