browse_categories:
- Analytics
code: https://github.com/signalfx/signalfx-agent
data_signature: plugin:"elasticsearch"
description: Monitor Elasticsearch using the SignalFx Smart agent.
display_name: Elasticsearch
featured: true
in_app_categories:
- servicesMonitored
logo_large: /images/repos/elasticsearch/img/integrations_elasticsearch%402x.png
logo_small: /images/repos/elasticsearch/img/integrations_elasticsearch.png
project_url: https://github.com/signalfx/integrations/tree/master/elasticsearch
useLegacyBuild: true
