code: https://github.com/signalfx/collectd/blob/master/src/df.c
description: 'The DF plugin for collectd collects file system usage information: how
  much space on a mounted partition is used and how much is available. '
display_name: DF (Disk Free)
featured: false
logo_large: /images/repos/collectd/img/integrations_collectd%402x.png
logo_small: /images/repos/collectd/img/integrations_collectd.png
project_url: https://github.com/signalfx/integrations/tree/master/collectd-df
useLegacyBuild: true
