browse_categories:
- Management Tools
code: https://github.com/signalfx
data_signature: metric_source:"NewRelic"
description: SignalFx's integration with New Relic.
display_name: New Relic
featured: false
logo_large: /images/repos/newrelic/img/integrations_newrelic.png
logo_small: /images/repos/newrelic/img/integrations_newrelic.png
useLegacyBuild: true
