{ "display_name":"Cassandra",
  "description": "Monitor Cassandra using the SignalFx collectd agent.",
  "project_url": "https://github.com/signalfx/integrations/tree/master/collectd-cassandra",
  "code": "https://github.com/signalfx/collectd/blob/master/bindings/java/org/collectd/java/GenericJMX.java",
  "featured": true,
  "logo_large": "/images/repos/collectd-cassandra/img/integrations_cassandra%402x.png",
  "logo_small": "/images/repos/collectd-cassandra/img/integrations_cassandra.png",
  "data_signature": "sf_metric:\"gauge.cassandra.ClientRequest.Read.Latency.50thPercentile\"",
  "in_app_categories": ["servicesMonitored"]
}
