browse_categories:
- Application Integration
code: https://github.com/signalfx/activemq-integration
data_signature: hostHasService:activemq
description: Monitor ActiveMQ using the SignalFx Smart Agent.
display_name: ActiveMQ
featured: true
in_app_categories:
- servicesMonitored
logo_large: /images/repos/activemq/img/integrations_activemq%402x.png
logo_small: /images/repos/activemq/img/integrations_activemq.png
project_url: https://github.com/signalfx/integrations/tree/master/activemq
