browse_categories:
- Storage
- Analytics
code: https://github.com/signalfx/collectd-hadoop
data_signature: plugin:"apache_hadoop"
description: Monitor Hadoop using the SignalFx Smart agent.
display_name: Hadoop
featured: false
in_app_categories:
- servicesMonitored
logo_large: /images/repos/hadoop/img/integrations_hadoop@2x.png
logo_small: /images/repos/hadoop/img/integrations_hadoop.png
project_url: https://github.com/signalfx/integrations/tree/master/hadoop
useLegacyBuild: true
