{ "display_name":"Redis collectd plugin",
  "description": "Redis collectd plugin",
  "project_url": "https://github.com/signalfx/integrations/tree/master/collectd-redis",
  "code": "https://github.com/signalfx/collectd/blob/master/src/redis.c",
  "featured": false,
  "logo_large": "/images/repos/collectd-redis/img/integrations_redis.png",
  "logo_small": "/images/repos/collectd-redis/img/integrations_redis%402x.png",
  "in_app_categories": ["servicesMonitored"]
}
