browse_categories:
- Networking & Content Delivery
code: https://github.com/cisco/bigmuddy-network-telemetry-stacks
description: Cisco IOS XR Integration for SignalFx
display_name: Cisco IOS XR Integration
featured: true
logo_large: /images/repos/logstash-ciscoxr/img/integrations_ciscoiosxr%402x.png
logo_small: /images/repos/logstash-ciscoxr/img/integrations_ciscoiosxr.png
project_url: https://github.com/signalfx/integrations/tree/master/logstash-ciscoxr
