{ "display_name":"SignalFx collectd agent",
  "description": "SignalFx's build of collectd, the open-source metrics collection agent.",
  "project_url": "https://github.com/signalfx/integrations/tree/master/collectd",
  "code": "https://github.com/signalfx/collectd",
  "featured": true,
  "logo_large": "/images/repos/collectd/img/integration_signalfx.png",
  "logo_small": "/images/repos/collectd/img/integration_signalfx.png",
  "data_signature": "plugin:\"signalfx-metadata\"",
  "in_app_categories": ["essential", "servicesMonitored"]
}
