code: https://github.com/signalfx/collectd
data_signature: _exists_:"depricated_check"
description: SignalFx's build of collectd, the open-source metrics collection agent.
display_name: SignalFx collectd agent
featured: true
in_app_categories:
- servicesMonitored
logo_large: /images/repos/collectd/img/integration_signalfx.png
logo_small: /images/repos/collectd/img/integration_signalfx.png
project_url: https://github.com/signalfx/integrations/tree/master/collectd
sort_order: 1
