browse_categories:
- Database
code: https://aws.amazon.com/elasticache/
data_signature: namespace:"AWS/ElastiCache"
description: SignalFx's integration with Amazon ElastiCache.
display_name: Amazon ElastiCache
featured: false
in_app_categories:
- AWSservicesMonitored
logo_large: integration_awselasticache.png
logo_small: integration_awselasticache.png
project_url: https://github.com/signalfx/integrations/tree/master/aws-elasticache
useLegacyBuild: true
