browse_categories:
- Database
code: https://cloud.google.com/bigtable
data_signature: service:"bigtable"
description: SignalFx's integration with Google Cloud Bigtable
display_name: Google Cloud Bigtable
featured: false
in_app_categories:
- GCPServicesMonitored
logo_large: integration_googlecloudbigtable%402x.png
logo_small: integration_googlecloudbigtable.png
project_url: https://github.com/signalfx/integrations/tree/master/google-cloud-bigtable
useLegacyBuild: true
