browse_categories:
- Networking & Content Delivery
code: https://github.com/signalfx/collectd-nginx-plus
data_signature: plugin:"nginx-plus"
description: Monitor NGINX Plus using the SignalFx collectd plugin.
display_name: NGINX Plus
featured: false
in_app_categories:
- servicesMonitored
logo_large: /images/repos/collectd-nginx-plus/img/integrations_nginxplus%402x.png
logo_small: /images/repos/collectd-nginx-plus/img/integrations_nginxplus.png
project_url: https://github.com/signalfx/integrations/tree/master/collectd-nginx-plus
useLegacyBuild: true
