browse_categories:
- Database
code: https://aws.amazon.com/redshift/
data_signature: namespace:"AWS/Redshift"
description: SignalFx's integration with Amazon Redshift.
display_name: Amazon Redshift
featured: false
in_app_categories:
- AWSservicesMonitored
logo_large: integration_awsredshift%402x.png
logo_small: integration_awsredshift.png
project_url: https://github.com/signalfx/integrations/tree/master/aws-redshift
useLegacyBuild: true
