browse_categories:
- Development Tools
code: https://github.com/signalfx/collectd-jenkins
data_signature: plugin:"jenkins"
description: Monitor Jenkins using the SignalFx collectd agent.
display_name: Jenkins
featured: false
in_app_categories:
- servicesMonitored
logo_large: /images/repos/jenkins/img/integrations_jenkins%402x.png
logo_small: /images/repos/jenkins/img/integrations_jenkins.png
project_url: https://github.com/signalfx/integrations/tree/master/jenkins
useLegacyBuild: true
