browse_categories:
- Application Integration
code: https://aws.amazon.com/sns/
data_signature: namespace:"AWS/SNS"
description: SignalFx's integration with Amazon Simple Notification Service (SNS).
display_name: Amazon SNS
featured: false
in_app_categories:
- AWSservicesMonitored
logo_large: integration_awssns.png
logo_small: integration_awssns.png
project_url: https://github.com/signalfx/integrations/tree/master/aws-sns
useLegacyBuild: true
