browse_categories:
- Database
code: https://github.com/signalfx/signalfx-agent/tree/master/internal/monitors/telegraf/monitors/mssqlserver
data_signature: sf_metric:"sqlserver_server_properties.db_online"
description: Monitor Microsoft SQL Server
display_name: Microsoft SQL Server
featured: false
in_app_categories:
- servicesMonitored
logo_large: /images/repos/microsoft-sql-server/img/integration_microsoftsqlserver%402x.png
logo_small: /images/repos/microsoft-sql-server/img/integration_microsoftsqlserver.png
project_url: https://github.com/signalfx/signalfx-agent/blob/master/docs/monitors/telegraf-sqlserver.md
