browse_categories:
- Compute
- Containers
code: https://azure.microsoft.com/en-us/services/batch/
data_signature: resource_type:"Microsoft.Batch/batchAccounts"
description: SignalFx's integration with Azure Batch
display_name: Azure Batch
featured: false
in_app_categories:
- AzureServicesMonitored
logo_large: integrations_azurebatch%402x.png
logo_small: integrations_azurebatch.png
project_url: https://github.com/signalfx/integrations/tree/master/azure-batch
useLegacyBuild: true
