{ "display_name":"Mesos collectd plugin",
  "description": "A collectd plugin for Apache Mesos using collectd's Python plugin.",
  "project_url": "https://github.com/signalfx/collectd-mesos",
  "code": "https://github.com/signalfx/integrations/tree/master/collectd-mesos",
  "featured": true,
  "logo_large": "/images/repos/collectd-mesos/img/integrations_mesos%402x.png",
  "logo_small": "/images/repos/collectd-mesos/img/integrations_mesos.png",
  "in_app_categories": ["Monitoring Services"] 
}
