{ "display_name":"Mesos",
  "description": "Monitor Apache Mesos using the SignalFx collectd agent.",
  "project_url": "https://github.com/signalfx/integrations/tree/master/collectd-mesos",
  "code": "https://github.com/signalfx/collectd-mesos",
  "featured": true,
  "logo_large": "/images/repos/collectd-mesos/img/integrations_mesos%402x.png",
  "logo_small": "/images/repos/collectd-mesos/img/integrations_mesos.png",
  "in_app_categories": ["servicesMonitored"]
}
