browse_categories:
- Compute
- Containers
code: https://github.com/signalfx/collectd-mesos
data_signature: plugin:"mesos"
description: Monitor Apache Mesos using the SignalFx collectd agent.
display_name: Mesos
featured: true
in_app_categories:
- servicesMonitored
logo_large: /images/repos/collectd-mesos/img/integrations_mesos%402x.png
logo_small: /images/repos/collectd-mesos/img/integrations_mesos.png
project_url: https://github.com/signalfx/integrations/tree/master/collectd-mesos
useLegacyBuild: true
