browse_categories:
- Database
code: https://github.com/signalfx/collectd-couchdb
data_signature: plugin:"couchdb"
description: Monitor CouchDB using the SignalFx collectd agent.
display_name: CouchDB
featured: false
in_app_categories:
- servicesMonitored
logo_large: /images/repos/collectd-couchdb/img/integrations_couchdb%402x.png
logo_small: /images/repos/collectd-couchdb/img/integrations_couchdb.png
project_url: https://github.com/signalfx/integrations/tree/master/collectd-couchdb
useLegacyBuild: true
