code: https://github.com/signalfx/iostat-collectd-python
description: Monitor IOStat metrics
display_name: IOStat
featured: false
logo_large: /images/repos/collectd-docker/img/integrations_iostat%402x.png
logo_small: /images/repos/collectd-docker/img/integrations_iostat.png
project_url: https://github.com/signalfx/integrations/tree/master/collectd-iostat
useLegacyBuild: true
