code: https://github.com/signalfx/Metrics.NET.SignalFX
description: SignalFx Integration with Windows Metrics.NET
display_name: Metrics.NET
featured: false
logo_large: /images/repos/win-metrics.net/img/integrations_windows%402x.png
logo_small: /images/repos/win-metrics.net/img/integrations_windows.png
project_url: https://github.com/signalfx/integrations/tree/master/win-metrics.net
