{ "display_name":"Aggregation",
  "description": "SignalFx uses the aggregation plugin for collectd to aggregate per-CPU metrics into overall sum and average per host.",
  "project_url": "https://github.com/signalfx/integrations/tree/master/collectd-aggregation",
  "code": "https://github.com/signalfx/collectd/blob/master/src/aggregation.c",
  "featured": false,
  "logo_large": "/images/repos/collectd/img/integrations_collectd%402x.png",
  "logo_small": "/images/repos/collectd/img/integrations_collectd.png"
},
