browse_categories:
- Management Tools
code: https://github.com/signalfx/appd-integration
description: The SignalFx AppDynamics integration brings metrics captured through
  AppDynamics into SignalFx.
display_name: AppDynamics
featured: false
in_app_categories:
- servicesMonitored
logo_large: /images/repos/appdynamics/img/integrations_appdynamics%402x.png
logo_small: /images/repos/appdynamics/img/integrations_appdynamics.png
project_url: https://github.com/signalfx/integrations/tree/master/appdynamics
useLegacyBuild: true
