browse_categories:
- Application Integration
- Internet of Things
code: https://azure.microsoft.com/en-us/services/logic-apps/
data_signature: resource_type:"Microsoft.Logic/workflows"
description: SignalFx's integration with Azure Logic Apps
display_name: Azure Logic Apps
featured: false
in_app_categories:
- AzureServicesMonitored
logo_large: integrations_azurelogicapps%402x.png
logo_small: integrations_azurelogicapps.png
project_url: https://github.com/signalfx/integrations/tree/master/azure-logic-app
