{ "display_name":"Load",
  "description": "Monitor system load with the Load collectd plugin",
  "project_url": "https://github.com/signalfx/integrations/tree/master/collectd-load",
  "code": "https://github.com/signalfx/collectd/blob/master/src/load.c",
  "featured": false,
  "logo_large": "/images/repos/collectd/img/integrations_collectd%402x.png",
  "logo_small": "/images/repos/collectd/img/integrations_collectd.png"
}
