code: https://github.com/signalfx/signalfx-collectd-plugin
data_signature: plugin:"signalfx-metadata"
description: The SignalFx plugin for collectd sends metadata about its host to SignalFx.
display_name: SignalFx plugin for collectd
featured: false
logo_large: /images/repos/collectd-signalfx/img/integrations_signalfx-collectd-plugin%402x.png
logo_small: /images/repos/collectd-signalfx/img/integrations_signalfx-collectd-plugin.png
project_url: https://github.com/signalfx/integrations/tree/master/collectd-signalfx
useLegacyBuild: true
