{ "display_name":"ActiveMQ",
  "description": "Monitor ActiveMQ using the SignalFx collectd agent.",
  "project_url": "https://github.com/signalfx/integrations/tree/master/collectd-activemq",
  "code": "https://github.com/signalfx/activemq-integration",
  "featured": true,
  "logo_large": "/images/repos/collectd-activemq/img/integrations_activemq%402x.png",
  "logo_small": "/images/repos/collectd-activemq/img/integrations_activemq.png",
  "in_app_categories": ["servicesMonitored"]
},
