code: https://github.com/signalfx/collectd/blob/master/src/interface.c
description: Monitor network interfaces using the SignalFx collectd agent.
display_name: Interface
featured: false
logo_large: /images/repos/collectd/img/integrations_collectd%402x.png
logo_small: /images/repos/collectd/img/integrations_collectd.png
project_url: https://github.com/signalfx/integrations/tree/master/collectd-interface
useLegacyBuild: true
