code: https://github.com/signalfx/signalfx-agent
data_signature: plugin:"host-metadata"
description: SignalFx agent with auto-discovery that supersedes the original collectd
  agent
display_name: ' SignalFx SmartAgent'
featured: true
in_app_categories:
- essential
- servicesMonitored
logo_large: /images/repos/collectd/img/integration_smartagent@2x.png
logo_small: /images/repos/collectd/img/integration_smartagent.png
project_url: https://github.com/signalfx/signalfx-agent
sort_order: 0
useLegacyBuild: true
