{ "display_name":"Riak collectd plugin",
  "description": "Riak collectd plugin",
  "project_url": "https://github.com/signalfx/integrations/tree/master/collectd-riak",
  "code": "https://github.com/signalfx/collectd/blob/master/src/curl_json.c",
  "featured": false,
  "logo_large": "/images/repos/collectd-riak/img/integrations_riak.png",
  "logo_small": "/images/repos/collectd-riak/img/integrations_riak%402x.png"
},
