{ "display_name":"Disk",
  "description": "The Disk plugin for collectd collects performance statistics of hard disks and partitions. ",
  "project_url": "https://github.com/signalfx/integrations/tree/master/collectd-disk",
  "code": "https://github.com/signalfx/collectd/blob/master/src/disk.c",
  "featured": false,
  "logo_large": "/images/repos/collectd/img/integrations_collectd%402x.png",
  "logo_small": "/images/repos/collectd/img/integrations_collectd.png"
},
