browse_categories:
- Networking & Content Delivery
- Mobile Services
code: https://aws.amazon.com/api-gateway/
data_signature: namespace:"AWS/ApiGateway"
description: SignalFx's integration with Amazon API Gateway.
display_name: Amazon API Gateway
featured: false
in_app_categories:
- AWSservicesMonitored
logo_large: integration_awsapigateway@2x.png
logo_small: integration_awsapigateway.png
project_url: https://github.com/signalfx/integrations/tree/master/aws-api-gateway
useLegacyBuild: true
