code: https://github.com/signalfx/signalfx-statsd.net-plugin
description: SignalFx Integration for Windows StatsD.NET
display_name: StatsD.NET
featured: false
in_app_categories:
- servicesMonitored
logo_large: /images/repos/win-statsd.net/img/integrations_windows%402x.png
logo_small: /images/repos/win-statsd.net/img/integrations_windows.png
project_url: https://github.com/signalfx/integrations/tree/master/win-statsd.net
useLegacyBuild: true
