browse_categories:
- Web
code: https://github.com/signalfx/collectd/blob/master/src/apache.c
data_signature: plugin:"apache"
description: Monitor the Apache Webserver using the SignalFx Smart Agent.
display_name: Apache
featured: false
in_app_categories:
- servicesMonitored
logo_large: /images/repos/apache/img/integrations_apache%402x.png
logo_small: /images/repos/apache/img/integrations_apache.png
project_url: https://github.com/signalfx/integrations/tree/master/apache
useLegacyBuild: true
