{ "display_name":"AWS OpsWorks",
  "description": "SignalFx's integration with AWS OpsWorks.",
  "project_url": "https://github.com/signalfx/integrations/tree/master/aws-opsworks",
  "code": "https://aws.amazon.com/opsworks/",
  "featured": false,
  "logo_large": "integration_awsopsworks.png",
  "logo_small": "integration_awsopsworks.png",
  "in_app_categories": ["AWSservicesMonitored"]
},
