{ "display_name":"StatsD",
  "description": "The StatsD plugin for collectd aggregates and transmits metrics from StatsD.",
  "project_url": "https://github.com/signalfx/integrations/tree/master/collectd-statsd",
  "code": "https://github.com/signalfx/collectd/blob/master/src/statsd.c",
  "featured": false,
  "logo_large": "/images/repos/collectd-statsd/img/integrations_statsd%402x.png",
  "logo_small": "/images/repos/collectd-statsd/img/integrations_statsd.png",
  "data_signature": "plugin:\"statsd\"",
  "in_app_categories": ["servicesMonitored"]
},
