code: https://github.com/signalfx/collectd/blob/master/src/curl_json.c
description: collectd plugin to gather metrics through cURL in JSON format
display_name: cURL-JSON collectd plugin
featured: false
logo_large: /images/repos/collectd/img/integrations_collectd%402x.png
logo_small: /images/repos/collectd/img/integrations_collectd.png
project_url: https://github.com/signalfx/integrations/tree/master/collectd-curl-json
useLegacyBuild: true
