browse_categories:
- Database
code: https://github.com/signalfx/collectd/blob/master/src/redis.c
data_signature: plugin:"redis_info"
description: Monitor Redis using the SignalFx Smart Agent.
display_name: Redis
featured: false
in_app_categories:
- servicesMonitored
logo_large: /images/repos/redis/img/integrations_redis%402x.png
logo_small: /images/repos/redis/img/integrations_redis.png
project_url: https://github.com/signalfx/integrations/tree/master/redis
useLegacyBuild: true
