data_signature: sf_metric:"gateway.processedTraces"
description: "SignalFx's Smart Gateway for Microservices APM and NoSample\u2122\uFE0F Tail-Based Distributed Tracing"
display_name: SignalFx Smart Gateway
feature: apm
featured: true
in_app_categories:
- essential
logo_large: integration_smartgateway@2x.png
logo_small: integration_smartgateway.png
project_url: https://docs.signalfx.com/en/latest/apm/apm-overview/index.html
sort_order: 0
